###
GET http://localhost:9000/api HTTP/1.1

###
POST  http://localhost:9000/api HTTP/1.1
Content-Type: application/json

{
    "name":"angeles",
    "address":"cooperativa",
    "phone":"946566436"
}
###
POST  http://localhost:9000/api HTTP/1.1
Content-Type: application/json

{
    "name":"ana",
    "address":"palian",
    "phone":"946566436"
}

###
DELETE http://localhost:9000/api/2  HTTP/1.1

###
PUT  http://localhost:9000/api/2 HTTP/1.1
Content-Type: application/json

{
    "name":"ana",
    "address":"palian",
    "phone":"946566436"
}